// View Actions
export const COMPLETE_INITIAL_LOAD = 'COMPLETE_INITIAL_LOAD';
export const SET_LAYER_MENU_OPEN = 'SET_LAYER_MENU_OPEN';
export const OPEN_HELP = 'OPEN_HELP';
export const CLOSE_HELP = 'CLOSE_HELP';
export const OPEN_SHARE = 'OPEN_SHARE';
export const CLOSE_SHARE = 'CLOSE_SHARE';
export const SELECT_HELP_PAGE = 'SELECT_HELP_PAGE';
export const DISMISS_ALERT = 'DISMISS_ALERT';
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN';
export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';

// Map Actions
export const SET_LAYER_ACTIVE = 'SET_LAYER_ACTIVE';
export const SET_MAP_VIEW_MODE = 'SET_MAP_VIEW_MODE';
export const RESET_ORIENTATION = 'RESET_ORIENTATION';
export const SET_LAYER_OPACITY = 'SET_LAYER_OPACITY';
export const SET_LAYER_PALETTE = 'SET_LAYER_PALETTE';
export const INITIALIZE_MAP = 'INITIALIZE_MAP';
export const SET_MAP_VIEW = 'SET_MAP_VIEW';
export const SET_MAP_VIEW_INFO = 'SET_MAP_VIEW_INFO';
export const ZOOM_IN = 'ZOOM_IN';
export const ZOOM_OUT = 'ZOOM_OUT';
export const SET_TERRAIN_ENABLED = 'SET_TERRAIN_ENABLED';
export const SET_SCALE_UNITS = 'SET_SCALE_UNITS';
export const SET_BASEMAP = 'SET_BASEMAP';
export const HIDE_BASEMAP = 'HIDE_BASEMAP';
export const SET_MAP_DATE = 'SET_MAP_DATE';
export const INGEST_LAYER_CONFIG = 'INGEST_LAYER_CONFIG';
export const MERGE_LAYERS = 'MERGE_LAYERS';
export const ACTIVATE_DEFAULT_LAYERS = 'ACTIVATE_DEFAULT_LAYERS';
export const PIXEL_HOVER = 'PIXEL_HOVER';
export const START_CHANGING_OPACITY = 'START_CHANGING_OPACITY';
export const STOP_CHANGING_OPACITY = 'STOP_CHANGING_OPACITY';
export const START_CHANGING_POSITION = 'START_CHANGING_POSITION';
export const STOP_CHANGING_POSITION = 'STOP_CHANGING_POSITION';
export const MOVE_LAYER_TO_TOP = 'MOVE_LAYER_TO_TOP';
export const MOVE_LAYER_TO_BOTTOM = 'MOVE_LAYER_TO_BOTTOM';
export const MOVE_LAYER_UP = 'MOVE_LAYER_UP';
export const MOVE_LAYER_DOWN = 'MOVE_LAYER_DOWN';
export const INGEST_LAYER_PALETTES = 'INGEST_LAYER_PALETTES';

// Async Actions
export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const INITIAL_DATA_LOADED = 'INITIAL_DATA_LOADED';
export const LOAD_LAYER_PALETTES = 'LOAD_LAYER_PALETTES';
export const LAYER_PALETTES_LOADED = 'LAYER_PALETTES_LOADED';
export const LOAD_LAYERS = 'LOAD_LAYERS';
export const LAYERS_LOADED = 'LAYERS_LOADED';

// Date Slider Actions
export const BEGIN_DRAGGING = 'BEGIN_DRAGGING';
export const END_DRAGGING = 'END_DRAGGING';

// Misc
export const NO_ACTION = 'NO_ACTION';