// View Actions
export const COMPLETE_INITIAL_LOAD = 'COMPLETE_INITIAL_LOAD';
export const TOGGLE_LAYER_MENU = 'TOGGLE_LAYER_MENU';
export const OPEN_HELP = 'OPEN_HELP';
export const CLOSE_HELP = 'CLOSE_HELP';
export const SELECT_HELP_PAGE = 'SELECT_HELP_PAGE';
export const DISMISS_ALERT = "DISMISS_ALERT";
export const TOGGLE_FULL_SCREEN = "TOGGLE_FULL_SCREEN";
export const OPEN_SETTINGS = "OPEN_SETTINGS";
export const CLOSE_SETTINGS = "CLOSE_SETTINGS";

// Map Actions
export const TOGGLE_LAYER = 'TOGGLE_LAYER';
export const TOGGLE_2D_3D = 'TOGGLE_2D_3D';
export const RESET_ORIENTATION = 'RESET_ORIENTATION';
export const SET_LAYER_OPACITY = 'SET_LAYER_OPACITY';
export const SET_LAYER_PALETTE = 'SET_LAYER_PALETTE';
export const INITIALIZE_MAP = 'INITIALIZE_MAP';
export const SET_MAP_VIEW = 'SET_MAP_VIEW';
export const SET_MAP_VIEW_INFO = 'SET_MAP_VIEW_INFO';
export const ZOOM_IN = 'ZOOM_IN';
export const ZOOM_OUT = 'ZOOM_OUT';
export const TOGGLE_POLITICAL_BOUNDARIES = 'TOGGLE_POLITICAL_BOUNDARIES';
export const TOGGLE_PLACE_LABELS = 'TOGGLE_PLACE_LABELS';
export const TOGGLE_ENABLE_TERRAIN = 'TOGGLE_ENABLE_TERRAIN';
export const SET_SCALE_UNITS = 'SET_SCALE_UNITS';
export const SET_BASEMAP = 'SET_BASEMAP';
export const HIDE_BASEMAP = 'HIDE_BASEMAP';
export const SET_MAP_DATE = 'SET_MAP_DATE';
export const INGEST_LAYER_CONFIG = 'INGEST_LAYER_CONFIG';
export const MERGE_LAYERS = 'MERGE_LAYERS';
export const ACTIVATE_DEFAULT_LAYERS = 'ACTIVATE_DEFAULT_LAYERS';
export const PIXEL_HOVER = 'PIXEL_HOVER';
export const START_CHANGING_OPACITY = 'START_CHANGING_OPACITY';
export const STOP_CHANGING_OPACITY = 'STOP_CHANGING_OPACITY';

// Async Actions
export const LOAD_LAYERS = 'LOAD_LAYERS';
export const LAYERS_LOADED = 'LAYERS_LOADED';